### ISSUE TITLE
As a devop, I can consistently create new Azure VMs

### ISSUE THREAD

**Issue by pburkholder** [18F/azure-sandbox#6]
- [ ] Building on what we've already done, commit our current Jenkins template to GH w/ Key Vault to hide secrets
- [x] Determine if ARM is going to be available in US Gov by Sep 23.
- [ ] Rank suitability of Azure CLI, Terraform, Azure console for this work.

**Comment by ctro** [comment]
Azure console == the web UI right?

**Comment by pburkholder** [comment]
Terraform w/ Azure: https://doics.co/2015/08/13/using-terraform-with-microsoft-azure/

**Comment by pburkholder** [comment]
https://azure.microsoft.com/en-us/documentation/articles/key-vault-manage-with-cli/

```bash
$ azure group create KVexample eastus
$ azure provider list | grep KeyVault
data:    Microsoft.KeyVault                      NotRegistered

$ azure keyvault create --vault-name KV --resource-group KVexample --location eastus


```

**Comment by ctro** [comment]
FWIW, some of the caveats from that Terraform article should be fixed, notably TF Azure provider now uses ARM: https://www.terraform.io/docs/providers/azurerm/

**Comment by pburkholder** [comment]
I'm closing this issue since the work we were doing with AzureSM is now obsoleted. Feel free to re-open if its useful in some respect I don't see.
